language: haskell

install:
  - cabal install doctest markdown-unlit

script:
  -                      (cabal install --only-dependencies --enable-tests && cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test && cabal sdist && cabal install dist/hspec-wai-*.tar.gz)
  - (cd hspec-wai-json && cabal install --only-dependencies --enable-tests && cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test && cabal sdist && cabal install dist/hspec-wai-*.tar.gz)
  - doctest -isrc hspec-wai-json/src/Test/Hspec/Wai/JSON.hs
  - cabal install scotty
  - ghc --make -Wall -Werror -pgmLmarkdown-unlit README.lhs
